"""Signal 1: Groq LLM Classification.

A Groq-hosted LLM evaluates the semantic and stylistic characteristics of the
text (coherence, phrasing patterns, repetition, structure, polish) and returns
a STRUCTURED assessment:

    {
        "ai_probability": 0.0-1.0,   # likelihood the text is AI-generated
        "reasoning": "<short explanation>",
        "indicators": ["<observed signal>", ...]
    }

Probability scale:
    0.10 = likely human-written
    0.50 = uncertain
    0.90 = likely AI-generated

Blind spots (see planning.md): very short text, heavily edited human or AI
writing, and polished professional/creative writing that resembles AI output.
"""

import json
import os
import re

from groq import Groq

# Groq-hosted model used for classification. Swap freely; this is a current,
# fast, instruction-following model on Groq that supports JSON mode.
_MODEL = "llama-3.3-70b-versatile"

# Neutral assessment returned when the classifier cannot produce a usable
# result. 0.5 = "uncertain" so a failure never pushes a submission toward a
# confident AI/human label.
_FALLBACK = {
    "ai_probability": 0.5,
    "reasoning": "Classifier unavailable or returned an unusable response; "
    "defaulting to a neutral, uncertain score.",
    "indicators": [],
}

_SYSTEM_PROMPT = (
    "You are an expert text-provenance classifier. You assess whether a piece "
    "of writing was generated by an AI language model or written by a human. "
    "Consider coherence, phrasing patterns, repetition, structure, and how "
    "polished or formulaic the wording is.\n\n"
    "Respond ONLY with a JSON object of exactly this shape:\n"
    '{\n'
    '  "ai_probability": <number between 0 and 1>,\n'
    '  "reasoning": "<one or two sentences explaining the score>",\n'
    '  "indicators": ["<short phrase>", "..."]\n'
    "}\n\n"
    "ai_probability: 0 means almost certainly human-written, 1 means almost "
    "certainly AI-generated. indicators is a short list of the specific traits "
    "that drove your judgment. Do not include any text outside the JSON object."
)


def _build_client():
    """Create a Groq client from the GROQ_API_KEY environment variable."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError("GROQ_API_KEY is not set in the environment.")
    return Groq(api_key=api_key)


def _coerce_assessment(raw_content):
    """Turn the model's raw response text into a validated assessment dict."""
    data = None
    try:
        data = json.loads(raw_content)
    except (ValueError, TypeError):
        # Fallback: pull the first number out of free-form text.
        match = re.search(r"[-+]?\d*\.?\d+", raw_content or "")
        if not match:
            raise ValueError(f"No score found in response: {raw_content!r}")
        data = {"ai_probability": float(match.group())}

    score = float(data.get("ai_probability"))
    return {
        # Clamp defensively in case the model returns something out of range.
        "ai_probability": max(0.0, min(1.0, score)),
        "reasoning": data.get("reasoning", ""),
        "indicators": data.get("indicators", []),
    }


def classify_text(text, client=None):
    """Return a structured LLM assessment of whether ``text`` is AI-generated.

    Args:
        text: The raw submission text to evaluate.
        client: Optional pre-built Groq client (useful for testing). When
            omitted, a client is created from the GROQ_API_KEY env var.

    Returns:
        A dict with keys ``ai_probability`` (float in [0, 1]), ``reasoning``
        (str), and ``indicators`` (list of str). On any API or parsing failure,
        returns the neutral fallback assessment rather than raising, so callers
        stay resilient.
    """
    if not text or not text.strip():
        return dict(_FALLBACK)

    client = client or _build_client()

    try:
        response = client.chat.completions.create(
            model=_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        raw_content = response.choices[0].message.content
        return _coerce_assessment(raw_content)
    except Exception:
        # Network errors, rate limits, malformed responses, etc. Degrade to a
        # neutral assessment so a single signal failure never crashes callers.
        return dict(_FALLBACK)


if __name__ == "__main__":
    # Independent test harness (Milestone 3 verification). Run from the project
    # root with:  python -m signals.llm_detector
    from dotenv import load_dotenv

    load_dotenv()  # pull GROQ_API_KEY out of .env

    samples = {
        "clearly human": "ugh, monday again. spilled coffee on my notes lol. "
        "gonna be one of those weeks i can already tell.",
        "clearly AI": "In conclusion, leveraging synergistic methodologies "
        "enables stakeholders to optimize outcomes across multiple dimensions "
        "while ensuring sustainable, scalable, and impactful results.",
        "short text": "Hello there.",
        "long human": "I spent the whole weekend rewiring the old lamp my "
        "grandfather left me. Half the screws were stripped and I swore at it "
        "more than once, but when it finally flickered on I just sat there "
        "grinning like an idiot. Funny how a busted lamp can do that.",
    }

    for label, sample in samples.items():
        result = classify_text(sample)
        print(f"\n=== {label} ===")
        print(f"  ai_probability: {result['ai_probability']:.2f}")
        print(f"  reasoning:      {result['reasoning']}")
        print(f"  indicators:     {result['indicators']}")
